### ISSUE TITLE
Attached JWS

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/core-protocol#2]
The example given for "attached JWS" in incorrect: missing JWS headers, incorrect `proof` value. Here's a better one for your base64 pleasure:

``
eyJhbGciOiJSUzI1NiIsImtpZCI6IktBZ05wV2JSeXk5TWYycmlrbDQ5OExUaE1ydmtiWldIVlNRT0JDNFZIVTQiLCJodG0iOiJwb3N0IiwiaHR1IjoiL3R4IiwidHMiOjE2MDM4MDA3ODN9.eyJjYXBhYmlsaXRpZXMiOltdLCJjbGllbnQiOnsia2V5Ijp7Imp3ayI6eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsImtpZCI6IktBZ05wV2JSeXk5TWYycmlrbDQ5OExUaE1ydmtiWldIVlNRT0JDNFZIVTQiLCJuIjoibGxXbUhGOFhBMktOTGRteE9QM2t4RDlPWTc2cDBTcjM3amZoejk0YTkzeG0yRk5xb1NQY1JaQVBkMGxxRFM4TjNVaWE1M2RCMjNaNTlPd1k0YnBNX1ZmOEdKdnZwdExXbnhvMVB5aG1Qci1lY2RTQ1JRZFRjX1pjTUY0aFJWNDhxcWx2dUQwbXF0Y0RiSWtTQkR2Y2NKbVpId2ZUcERIaW5UOHR0dmNWUDhWa0FNQXE0a1ZhenhPcE1vSVJzb3lFcF9lQ2U1cFN3cUhvMGRhQ1dOS1ItRXBLbTZOaU90ZWRGNE91bXQ4TkxLVFZqZllnRkhlQkRkQ2JyckVUZDR2Qk13RHRBbmpQcjNDVkN3d3gyYkFRVDZTbHhGSjNmajJoaHlJcHE3cGM4clppYjVqTnlYS3dmQnVrVFZZWm96a3NodC1Mb2h5QVNhS3BZVHA4THROWi13In0sInByb29mIjoiandzIn0sIm5hbWUiOiJNeSBGaXN0IENsaWVudCIsInVyaSI6Imh0dHA6Ly9sb2NhbGhvc3QvY2xpZW50L2NsaWVudElEIn0sImludGVyYWN0Ijp7ImNhbGxiYWNrIjp7Im1ldGhvZCI6InJlZGlyZWN0Iiwibm9uY2UiOiJkOTAyMTM4ODRiODQwOTIwNTM4YjVjNTEiLCJ1cmkiOiJodHRwOi8vbG9jYWxob3N0L2NsaWVudC9yZXF1ZXN0LWRvbmUifSwicmVkaXJlY3QiOnRydWV9LCJyZXNvdXJjZXMiOnsiYWN0aW9ucyI6WyJyZWFkIiwicHJpbnQiXSwibG9jYXRpb25zIjpbImh0dHA6Ly9sb2NhbGhvc3QvcGhvdG9zIl0sInR5cGUiOiJwaG90by1hcGkifSwic3ViamVjdCI6eyJzdWJfaWRzIjpbImlzcy1zdWIiLCJlbWFpbCJdfX0.LUyZ8_fERmxbYARq8kBYMwzcd8GnCAKAlo2ZSYLRRNAYWPrp2XGLJOvg97WK1idf_LB08OJmLVsCXxCvn9mgaAkYNL_ZjHcusBvY1mNo0E1sdTEr31CVKfC-6WrZCscb8YqE4Ayhh0Te8kzSng3OkLdy7xN4xeKuHzpF7yGsM52JZ0cBcTo6WrYEfGdr08AWQJ59ht72n3jTsmYNy9A6I4Wrvfgj3TNxmwYojpBAicfjnzA1UVcNm9F_xiSz1_y2tdH7j5rVqBMQife-k9Ewk95vr3lurthenliYSNiUinVfoW1ybnaIBcTtP1_YCxg_h1y-B5uZEvYNGCuoCqa6IQ
``

**Comment by jricher** [comment]
At this stage, most of the examples need to be reworked and/or re-generated, especially including things with signatures. They were all originally pulled from a running system based on an older version of the I-D, and so edits to them have been by hand so far. This is a helpful start, so thanks!
