### ISSUE TITLE
"updated_at" Format

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/core-protocol#26]
Yaron: 3.4: "updated_at": Unix time is nice, but for absolute time it's common to use ISO 8601 format.

Justin: I stole this field from OIDC, but I’m fine with any format here, so if there’s no outcry we should change it in the next revision.

**Comment by jricher** [comment]
This has been changed to ISO 8601 format in 7d6c4580a11f2cd352d67121c8eeb68326b3d009
